exec-once = waybar
exec-once = hyprctl setcursor catppuccin-mocha-lavender-cursors 22
exec-once = hyprpaper
#Notif daemon
exec-once = mako

# dbus session
exec-once = dbus-launch --sh-syntax --exit-with-session

# clipboard history
exec-once = wl-paste --watch cliphist store

#Auto mounting external storage and USBs
exec-once = udiskie --tray
